<a href="https://colab.research.google.com/github/Sonjoy209164/Computer-Vision/blob/main/tensorflowtensor_neuralearn_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 print("hello")

hello


In [ ]:
import tensorflow as tf

# Creatig a ND tensor

## 1.Tensor 0 D

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)


tf.Tensor(4, shape=(), dtype=int32)


## 2.Tensor 1D

In [ ]:
tensor_zero_d =tf.constant([2,1,3.]);
tensor_zero_d =tf.constant([2,1,3]);
print(tensor_zero_d)

tf.Tensor([2 1 3], shape=(3,), dtype=int32)


## 3.Tensor 2D

In [ ]:
tensor_two_d= tf.constant([[1,2,3],[4,5,6]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


## 4.Tensor 3D

In [ ]:
tensor_three_d= tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],dtype=tf.float32)
casted_tensor_three_d= tf.cast(tensor_three_d,dtype=tf.int32)
print(tensor_three_d)
print(tensor_three_d.shape)
print(casted_tensor_three_d)
tensor_bool=tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float32)
(2, 2, 3)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor([ True  True False], shape=(3,), dtype=bool)


## 5.Tensor string

In [ ]:
tensor_string=tf.constant(["hello","world"])
print(tensor_string)

tf.Tensor([b'hello' b'world'], shape=(2,), dtype=string)


## 6.create numpy array in tensor  

In [ ]:
import numpy as np

In [ ]:
np_array = np.ndarray([1, 2, 3])
print(np_array)

[[[2.00000047e+00 5.12000123e+02 8.19200197e+03]
  [1.31072032e+05 5.24288127e+05 2.09715251e+06]]]


In [ ]:
np_array_tensor=tf.convert_to_tensor(np_array)
print(np_array_tensor)

tf.Tensor(
[[[2.00000047e+00 5.12000123e+02 8.19200197e+03]
  [1.31072032e+05 5.24288127e+05 2.09715251e+06]]], shape=(1, 2, 3), dtype=float64)


## 7.eye tensor

In [ ]:
eye_tensor =tf.eye(
    num_rows=3,
    num_columns=5,
    batch_shape=[2,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]]], shape=(2, 3, 3, 5), dtype=float32)


## 8.To fill

In [ ]:
fill_tensor=tf.fill([2,3],5)
print(fill_tensor)
# fill_tensor.fill(dims,value,name=None)

tf.Tensor(
[[5 5 5]
 [5 5 5]], shape=(2, 3), dtype=int32)


In [ ]:
# create a tensor of all ones that has the same shape as the input tensor.
tf.ones_like(
    fill_tensor,dtype=None,name=None
)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [ ]:
zero_tensor=tf.ones_like(fill_tensor)
print(zero_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [ ]:
# return a tensor same as input tensor
