<a href="https://colab.research.google.com/github/Sonjoy209164/Computer-Vision/blob/main/tensorflowtensor_neuralearn_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


In [1]:
import tensorflow as tf

# Creatig a ND tensor

1.Tensor 0 D

In [5]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)


tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([2 1 3], shape=(3,), dtype=int32)


2.Tensor 1D

In [8]:
tensor_zero_d =tf.constant([2,1,3.]);
tensor_zero_d =tf.constant([2,1,3]);
print(tensor_zero_d)

tf.Tensor([2 1 3], shape=(3,), dtype=int32)


3.Tensor 2D

In [9]:
tensor_two_d= tf.constant([[1,2,3],[4,5,6]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


4.Tensor 3D

In [15]:
tensor_three_d= tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],dtype=tf.float32)
casted_tensor_three_d= tf.cast(tensor_three_d,dtype=tf.int32)
print(tensor_three_d)
print(tensor_three_d.shape)
print(casted_tensor_three_d)
tensor_bool=tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float32)
(2, 2, 3)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor([ True  True False], shape=(3,), dtype=bool)


5.Tensor string

In [16]:
tensor_string=tf.constant(["hello","world"])
print(tensor_string)

tf.Tensor([b'hello' b'world'], shape=(2,), dtype=string)
